<html>
  <head>
      <title>/view/ballots</title>
      <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  </head>
  <body>
    <h1>Information stored in tbl_ballots</h1>

    <table class="pure-table">
        <tr>
            <th>id</th>
            <th>electionIdentifier</th>
            <th>jsonData</th>
            <th>timestamp</th>
        </tr>

    <?php foreach($data['ballots'] as $ballot): ?>

        <tr>
            <td><?=$ballot->getId() ?></td>
            <td><?=$ballot->getElectionIdentifier() ?></td>
            <td><?=$ballot->getJsonData() ?></td>
            <td><?=$ballot->getTimestamp() ?></td>
        </tr>

    <?php endforeach; ?>
    </table>
  </body>
</html>
