<!--
/**
 *
 * abcVote (https://github.com/EVGStudents/abcVote)
 * Bulletin-Board for abcVote's e-voting applications
 *
 * ballots.phtml: template for generating a html view of stored ballots
 *
 * @author Sebastian Nellen <sebastian at nellen.it>
 */
-->

<html>
  <head>
      <title>/view/ballots</title>
      <link rel="stylesheet" href="https://abc.2488.ch/pure-min.css">
  </head>
  <body>
    <h1>Information stored in tbl_ballots</h1>

    <table class="pure-table">
        <tr>
            <th>id</th>
            <th>electionIdentifier</th>
            <th>jsonData</th>
            <th>timestamp</th>
        </tr>

    <?php foreach($data['ballots'] as $ballot): ?>

        <tr>
            <td><?=$ballot->getId() ?></td>
            <td><?=$ballot->getElectionIdentifier() ?></td>
            <td><?=$ballot->getJsonData() ?></td>
            <td><?=$ballot->getTimestamp() ?></td>
        </tr>

    <?php endforeach; ?>
    </table>
  </body>
</html>
