<!--
/**
 *
 * abcVote (https://github.com/EVGStudents/abcVote)
 * Bulletin-Board for abcVote's e-voting applications
 *
 * elections.phtml: template for generating a html view of stored elections
 *
 * @author Sebastian Nellen <sebastian at nellen.it>
 */
-->

<html>
  <head>
      <title>/view/elections</title>
      <link rel="stylesheet" href="https://abc.2488.ch/pure-min.css">
  </head>
  <body>
    <h1>Information stored in tblElections</h1>

    <table class="pure-table">
        <tr>
            <th>id</th>
            <th>jsonData</th>
            <th>electionTitle</th>
            <th>beginDate</th>
            <th>endDate</th>
            <th>coefficients</th>
            <th>appVersion</th>
        </tr>

    <?php foreach($data['elections'] as $election): ?>

        <tr>
            <td><?=$election->getId() ?></td>
            <td><?=substr($election->getJsonData(), 0, 100).'...' ?></td>
            <td><?=$election->getElectionTitle() ?></td>
            <td><?=$election->getBeginDate() ?></td>
            <td><?=$election->getEndDate() ?></td>
            <td><?=substr($election->getCoefficients(), 0, 100).'...' ?></td>
            <td><?=$election->getAppVersion() ?></td>
        </tr>

    <?php endforeach; ?>
    </table>
  </body>
</html>
