<html>
  <head>
      <title>/view/generators</title>
      <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  </head>
  <body>
    <h1>Information stored in tblGenerators</h1>

    <table class="pure-table">
        <tr>
            <th>generatorName</th>
            <th>generatorValue</th>
        </tr>

    <?php foreach($data['generators'] as $generator): ?>

        <tr>
            <td><?=$generator->getGeneratorName() ?></td>
            <td><?=$generator->getGeneratorValue() ?></td>
        </tr>

    <?php endforeach; ?>
    </table>
  </body>
</html>
