<html>
  <head>
      <title>/view/parameters</title>
      <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  </head>
  <body>
    <h1>Information stored in tblParameters</h1>

    <table class="pure-table">
        <tr>
            <th>parameterName</th>
            <th>parameterValue</th>
        </tr>

    <?php foreach($data['parameters'] as $parameter): ?>

        <tr>
            <td><?=$parameter->getParameterName() ?></td>
            <td><?=$parameter->getParameterValue() ?></td>
        </tr>

    <?php endforeach; ?>
    </table>
  </body>
</html>
