<!--
/**
 *
 * abcVote (https://github.com/EVGStudents/abcVote)
 * Bulletin-Board for abcVote's e-voting applications
 *
 * parameters.phtml: template for generating a html view of stored parameters
 *
 * @author Sebastian Nellen <sebastian at nellen.it>
 */
-->

<html>
  <head>
      <title>/view/parameters</title>
      <link rel="stylesheet" href="https://abc.2488.ch/pure-min.css">
  </head>
  <body>
    <h1>Information stored in tblParameters</h1>

    <table class="pure-table">
        <tr>
            <th>parameterName</th>
            <th>parameterValue</th>
        </tr>

    <?php foreach($data['parameters'] as $parameter): ?>

        <tr>
            <td><?=$parameter->getParameterName() ?></td>
            <td><?=$parameter->getParameterValue() ?></td>
        </tr>

    <?php endforeach; ?>
    </table>
  </body>
</html>
