<!--
/**
 *
 * abcVote (https://github.com/EVGStudents/abcVote)
 * Bulletin-Board for abcVote's e-voting applications
 *
 * voters.phtml: template for generating a html view of stored voters
 *
 * @author Sebastian Nellen <sebastian at nellen.it>
 */
-->

<html>
  <head>
      <title>/view/voters</title>
      <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  </head>
  <body>
    <h1>Voters stored in tblVoters</h1>

    <table class="pure-table">
        <tr>
            <th>ID</th>
            <th>jsonData</th>
        </tr>

    <?php foreach($data['voters'] as $voter): ?>

        <tr>
            <td><?=$voter->getId() ?></td>
            <td><?=$voter->getJsonData() ?></td>
        </tr>

    <?php endforeach; ?>
    </table>
  </body>
</html>
